import fs from 'fs';

// 27 products mapped from https://kdv-group.com/ru/brand/9 (Бегемотик Бонди / Hippo Bondi)
const bondiProducts = [
  // === БИСКВИТЫ ===
  {
    id: 'prod_bondi_bisc_banana',
    sku: 'BND-BSC-BAN',
    barcode: '4607065538012',
    nameUz: 'HIPPO BO & Friends: Banan ta\'mli biskvit pirojnoye 32g',
    nameRu: 'Бисквитное пирожное HIPPO BO & friends с желейной начинкой со вкусом банана 32г',
    nameEn: 'HIPPO BO Biscuit Cake with Banana Jelly Filling 32g',
    categoryId: 'cat_bondi_biscuits',
    brand: 'Бегемотик Бонди',
    price: 3500,
    costPrice: 2200,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/d0a3237f25311021eb912461c17a326c.jpg',
    description: 'Yangi tabiiy tuxum asosida tayyorlangan, banan ta\'mli jeleli nachinkaga ega yumshoq biskvit pirojnoye. Palma moyisiz, bolalar uchun xavfsiz va mazali.',
    expiryDays: 180,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 450, br_chilanzar: 220, br_samarkand: 180 },
    minStockAlert: 50,
    tags: ['бонди', 'бисквит', 'банан', 'hippo bo', 'kdv', 'пирожное']
  },
  {
    id: 'prod_bondi_bisc_condmilk',
    sku: 'BND-BSC-SGU',
    barcode: '4607065538029',
    nameUz: 'HIPPO BO & Friends: Qaynatilgan quyultirilgan sutli biskvit pirojnoye 32g',
    nameRu: 'Бисквитное пирожное HIPPO BO & friends с начинкой «варёная сгущёнка» 32г',
    nameEn: 'HIPPO BO Biscuit Cake with Boiled Condensed Milk 32g',
    categoryId: 'cat_bondi_biscuits',
    brand: 'Бегемотик Бонди',
    price: 3500,
    costPrice: 2200,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/3364dd9ab5a31475983643450a840d16.jpg',
    description: 'Yangi tuxum va haqiqiy qaynatilgan quyultirilgan sut (varyonaya sgushyonka) nachinkali biskvit. Palma moyisiz.',
    expiryDays: 180,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 400, br_chilanzar: 200, br_samarkand: 150 },
    minStockAlert: 50,
    tags: ['бонди', 'бисквит', 'сгущенка', 'hippo bo', 'kdv']
  },
  {
    id: 'prod_bondi_bisc_raspberry',
    sku: 'BND-BSC-RAS',
    barcode: '4607065538036',
    nameUz: 'HIPPO BO & Friends: Malina sharbati bilan biskvit pirojnoye 32g',
    nameRu: 'Бисквитное пирожное HIPPO BO & friends с желейной начинкой со вкусом малины 32г',
    nameEn: 'HIPPO BO Biscuit Cake with Raspberry Juice Filling 32g',
    categoryId: 'cat_bondi_biscuits',
    brand: 'Бегемотик Бонди',
    price: 3500,
    costPrice: 2200,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/424c32d71e75083cae94f682306e4da1.jpg',
    description: 'Tabiiy malina sharbati qo\'shilgan jeleli nachinkaga ega nozik bolalar biskviti. Palma moyisiz.',
    expiryDays: 180,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 380, br_chilanzar: 190, br_samarkand: 160 },
    minStockAlert: 50,
    tags: ['бонди', 'бисквит', 'малина', 'hippo bo', 'kdv']
  },
  {
    id: 'prod_bondi_bisc_peach_strawb',
    sku: 'BND-BSC-PST',
    barcode: '4607065538043',
    nameUz: 'HIPPO BO & Friends: Shaftoli biskviti qulupnayli nachinka bilan 32g',
    nameRu: 'Бисквитное пирожное HIPPO BO & friends персиковое с клубничной начинкой 32г',
    nameEn: 'HIPPO BO Peach Biscuit Cake with Strawberry Filling 32g',
    categoryId: 'cat_bondi_biscuits',
    brand: 'Бегемотик Бонди',
    price: 3500,
    costPrice: 2200,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/be5ee5cd921ca949c4cd717cce24086a.jpg',
    description: 'Saralangan yangi tuxumda pishirilgan shaftoli xamirli va tabiiy qulupnay sharbatli nachinkali bolalar biskviti.',
    expiryDays: 180,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 350, br_chilanzar: 180, br_samarkand: 140 },
    minStockAlert: 40,
    tags: ['бонди', 'бисквит', 'персик', 'клубника', 'hippo bo']
  },

  // === ГЕМАТОГЕН ===
  {
    id: 'prod_bondi_hematogen_classic',
    sku: 'BND-HEM-40G',
    barcode: '4607065531013',
    nameUz: 'Begemotik Bondi: 100% Tabiiy Bolalar Gematogeni 40g',
    nameRu: 'Гематоген «Бегемотик Бонди» классический 40г',
    nameEn: 'Hematogen Begemotik Bondi Classic 40g',
    categoryId: 'cat_bondi_hematogen',
    brand: 'Бегемотик Бонди',
    price: 4500,
    costPrice: 2800,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/baf0d4d5a039130fd83d3cd3fe817647.jpg',
    description: '100% tabiiy gematogen. Klassik retsept: quyultirilgan sut, patoka, shakar va qora oziq-ovqat albumini. Temir moddasiga boy, immunitetni mustahkamlaydi.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 600, br_chilanzar: 300, br_samarkand: 250 },
    minStockAlert: 60,
    tags: ['бонди', 'гематоген', 'железо', 'витамины', 'kdv']
  },

  // === ДЕТСКОЕ ПИТАНИЕ (ПЮРЕ В ПАУЧАХ 90г) ===
  {
    id: 'prod_bondi_puree_apple_blueb',
    sku: 'BND-PUR-APBL',
    barcode: '4607065537015',
    nameUz: 'Begemotik Bondi: Olma va Chernika meva pyuresi 90g (Pauch)',
    nameRu: 'Детское пюре «Бегемотик Бонди» Яблоко и черника 90г',
    nameEn: 'Baby Puree Begemotik Bondi Apple & Blueberry 90g',
    categoryId: 'cat_bondi_puree',
    brand: 'Бегемотик Бонди',
    price: 8500,
    costPrice: 5500,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/500181d12ce213bafb1fc97b095b3781.jpg',
    description: '100% tabiiy pishgan mevalardan pyure. Shakarsiz, kraxmali va konservantsiz. 5 oylikdan boshlab chaqaloqlar uchun tavsiya etiladi. Qulay qopqoqli pauch paketi.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 320, br_chilanzar: 160, br_samarkand: 140 },
    minStockAlert: 40,
    tags: ['бонди', 'пюре', 'яблоко', 'черника', 'детское питание']
  },
  {
    id: 'prod_bondi_puree_apple_pear',
    sku: 'BND-PUR-APPR',
    barcode: '4607065537022',
    nameUz: 'Begemotik Bondi: Olma va Nok meva pyuresi 90g (Pauch)',
    nameRu: 'Детское пюре «Бегемотик Бонди» Яблоко и груша 90г',
    nameEn: 'Baby Puree Begemotik Bondi Apple & Pear 90g',
    categoryId: 'cat_bondi_puree',
    brand: 'Бегемотик Бонди',
    price: 8500,
    costPrice: 5500,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/9a87f66e9e37a49d9633c2a67143bdba.jpg',
    description: '100% tabiiy meva pyuresi. Shakarsiz, kraxmalsiz, GMOsiz. 5 oylikdan boshlab chaqaloqlar uchun to\'yimli va yengil hazm bo\'luvchi taom.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 340, br_chilanzar: 170, br_samarkand: 150 },
    minStockAlert: 40,
    tags: ['бонди', 'пюре', 'яблоко', 'груша', 'детское питание']
  },
  {
    id: 'prod_bondi_puree_apple_pear_peach',
    sku: 'BND-PUR-APPC',
    barcode: '4607065537039',
    nameUz: 'Begemotik Bondi: Olma, Nok va Shaftoli meva pyuresi 90g',
    nameRu: 'Детское пюре «Бегемотик Бонди» Яблоко, груша и персик 90г',
    nameEn: 'Baby Puree Begemotik Bondi Apple, Pear & Peach 90g',
    categoryId: 'cat_bondi_puree',
    brand: 'Бегемотик Бонди',
    price: 8500,
    costPrice: 5500,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/2f188377aa50c573713975c64c94a7d6.jpg',
    description: 'Pishgan shirin olma, nok va xushbo\'y shaftolidan tayyorlangan quyuq va vitaminli bolalar pyuresi. Shakarsiz va bo\'yoqsiz.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 300, br_chilanzar: 150, br_samarkand: 130 },
    minStockAlert: 40,
    tags: ['бонди', 'пюре', 'яблоко', 'персик', 'груша']
  },
  {
    id: 'prod_bondi_puree_cereals',
    sku: 'BND-PUR-CER',
    barcode: '4607065537046',
    nameUz: 'Begemotik Bondi: Olma, Shaftoli, Banan va Donli un (Zlaki) 90g',
    nameRu: 'Детское пюре «Бегемотик Бонди» Яблоко, персик, банан, злаки 90г',
    nameEn: 'Baby Puree Begemotik Bondi Fruits & Cereals 90g',
    categoryId: 'cat_bondi_puree',
    brand: 'Бегемотик Бонди',
    price: 8900,
    costPrice: 5800,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/2b0b75fc96b2149ea8946691f3ef8054.jpg',
    description: 'Suli va guruch uni bilan boyitilgan tabiiy meva pyuresi (olma, shaftoli, banan). 6 oylikdan boshlab to\'yimli nonushta yoki kechki taom uchun ajoyib.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 360, br_chilanzar: 180, br_samarkand: 160 },
    minStockAlert: 40,
    tags: ['бонди', 'пюре', 'злаки', 'банан', 'персик', 'детское питание']
  },
  {
    id: 'prod_bondi_puree_cookies',
    sku: 'BND-PUR-COK',
    barcode: '4607065537053',
    nameUz: 'Begemotik Bondi: Olma, Banan va Bolalar Pechenyesi bilan pyure 90g',
    nameRu: 'Детское пюре «Бегемотик Бонди» Яблоко, банан, печенье 90г',
    nameEn: 'Baby Puree Begemotik Bondi Apple, Banana & Cookies 90g',
    categoryId: 'cat_bondi_puree',
    brand: 'Бегемотик Бонди',
    price: 8900,
    costPrice: 5800,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/e8f897aa7b899ad2386a105110fafe66.jpg',
    description: 'Tabiiy mevalar va mayin Bondi bolalar pechenyesi qo\'shilgan to\'yimli desert pyure. 6 oylikdan boshlab chaqaloqlar uchun.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 390, br_chilanzar: 200, br_samarkand: 170 },
    minStockAlert: 40,
    tags: ['бонди', 'пюре', 'печенье', 'банан', 'яблоко']
  },

  // === МАРМЕЛАД ЖЕВАТЕЛЬНЫЙ ===
  {
    id: 'prod_bondi_marm_30g',
    sku: 'BND-MRM-30G',
    barcode: '4607065532010',
    nameUz: 'HIPPO BONDI: Meva sharbatli chaynash marmeladi 30g',
    nameRu: 'Жевательный мармелад HIPPO BONDI & friends с соком ягод и фруктов 30г',
    nameEn: 'Gummy Marmalade HIPPO BONDI with Fruit Juice 30g',
    categoryId: 'cat_bondi_marmalade',
    brand: 'Бегемотик Бонди',
    price: 3200,
    costPrice: 1900,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/8ebeb10c50731c3c41f95d2d547e42a6.jpg',
    description: '100% tabiiy olma, gilos, qulupnay, limon, apelsin va qora smorodina sharbatidan marmelad. 0% yog\', C, B5, B6, PP vitaminlari va foliy kislotasiga boy. Begemotcha shakllarida.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 550, br_chilanzar: 280, br_samarkand: 220 },
    minStockAlert: 50,
    tags: ['бонди', 'мармелад', 'жевательный', 'витамины', 'kdv']
  },
  {
    id: 'prod_bondi_marm_70g',
    sku: 'BND-MRM-70G',
    barcode: '4607065532027',
    nameUz: 'HIPPO BONDI: Meva sharbatli chaynash marmeladi 70g',
    nameRu: 'Жевательный мармелад HIPPO BONDI & friends с соком ягод и фруктов 70г',
    nameEn: 'Gummy Marmalade HIPPO BONDI with Fruit Juice 70g',
    categoryId: 'cat_bondi_marmalade',
    brand: 'Бегемотик Бонди',
    price: 6500,
    costPrice: 4000,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/bc48e301f4bb7bdcd2bfcfca63cf282a.jpg',
    description: 'Katta qulay paketda mevali begemotcha marmeladlari. C, B5, B6, PP vitaminlari bilan boyitilgan.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 480, br_chilanzar: 240, br_samarkand: 200 },
    minStockAlert: 40,
    tags: ['бонди', 'мармелад', 'жевательный', 'витамины']
  },
  {
    id: 'prod_bondi_marm_halves_100g',
    sku: 'BND-MRM-100G',
    barcode: '4607065532034',
    nameUz: 'HIPPO BONDI: Konstruktor hayvonchalar shaklidagi marmelad 100g',
    nameRu: 'Жевательный мармелад HIPPO BONDI в форме половинок животных 100г',
    nameEn: 'Gummy Marmalade HIPPO BONDI Animals Halves 100g',
    categoryId: 'cat_bondi_marmalade',
    brand: 'Бегемотик Бонди',
    price: 8800,
    costPrice: 5600,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/5254bad5cf5fe3445ccffbac400d6e99.jpg',
    description: 'Qiziqarli o\'yinli marmelad-konstruktor: bolalar begemot, sher va toshbaqa yarimlarini bir-biriga ulab yangi qahramonlar yaratishi mumkin! Tabiiy pektinda.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 420, br_chilanzar: 210, br_samarkand: 170 },
    minStockAlert: 40,
    tags: ['бонди', 'мармелад', 'конструктор', 'половинки', 'животные']
  },

  // === ПЕЧЕНЬЕ ФАСОВАННОЕ (БОНДИ БОЛАЛАР ПЕЧЕНЬЕСИ) ===
  {
    id: 'prod_bondi_cookie_iron_180g',
    sku: 'BND-CK-IR180',
    barcode: '4607065533017',
    nameUz: 'Begemotik Bondi: Temir bilan boyitilgan bolalar pechenyesi 180g',
    nameRu: 'Детское печенье «Бегемотик Бонди» обогащённое железом 180г',
    nameEn: 'Baby Biscuits Begemotik Bondi with Iron 180g',
    categoryId: 'cat_bondi_cookies',
    brand: 'Бегемотик Бонди',
    price: 12500,
    costPrice: 8200,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/2f7b63809efa10b1174adeed067b35bb.jpg',
    description: 'Eng kichkintoylar uchun foydali va yumshoq pechenye. 6 oylikdan boshlab. Tabiiy sut, temir va PP, B1, B2, C vitaminlari bilan boyitilgan. Sutda yoki sharbatda oson eriydi.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 520, br_chilanzar: 260, br_samarkand: 210 },
    minStockAlert: 50,
    tags: ['бонди', 'печенье', 'железо', 'детское печенье', 'kdv']
  },
  {
    id: 'prod_bondi_cookie_letters_80g',
    sku: 'BND-CK-LET80',
    barcode: '4607065533024',
    nameUz: 'Begemotik Bondi: "Harflar va Raqamlar" bolalar pechenyesi 80g (Zip)',
    nameRu: 'Детское печенье «Бегемотик Бонди» «Изучаем буквы и цифры» 80г',
    nameEn: 'Baby Biscuits Begemotik Bondi Letters & Numbers 80g',
    categoryId: 'cat_bondi_cookies',
    brand: 'Бегемотик Бонди',
    price: 7800,
    costPrice: 4900,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/d4668aafc3f80d8fedb4f025bdb8a2eb.jpg',
    description: 'Harflar va raqamlar shaklidagi tangacha pechenyelar. Qulay zip-qulfli paket. 5 oylikdan boshlab bolalarga alifbo va hisobni o\'rganish uchun ideal.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 410, br_chilanzar: 200, br_samarkand: 180 },
    minStockAlert: 40,
    tags: ['бонди', 'печенье', 'буквы', 'цифры', 'zip']
  },
  {
    id: 'prod_bondi_cookie_iodine_180g',
    sku: 'BND-CK-IOD180',
    barcode: '4607065533031',
    nameUz: 'Begemotik Bondi: Yod bilan boyitilgan bolalar pechenyesi 180g',
    nameRu: 'Детское печенье «Бегемотик Бонди» обогащённое йодом 180г',
    nameEn: 'Baby Biscuits Begemotik Bondi with Iodine 180g',
    categoryId: 'cat_bondi_cookies',
    brand: 'Бегемотик Бонди',
    price: 12500,
    costPrice: 8200,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/e2f820eed1d5bcd153f15ec9b9753e84.jpg',
    description: 'Bolaning aqliy rivojlanishi va qalqonsimon bezi faoliyati uchun zarur yod hamda vitaminlar (PP, B1, B2, C) bilan boyitilgan mayin pechenye.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 460, br_chilanzar: 230, br_samarkand: 190 },
    minStockAlert: 40,
    tags: ['бонди', 'печенье', 'йод', 'детское печенье']
  },
  {
    id: 'prod_bondi_cookie_calcium_180g',
    sku: 'BND-CK-CAL180',
    barcode: '4607065533048',
    nameUz: 'Begemotik Bondi: Kalsiy bilan boyitilgan bolalar pechenyesi 180g',
    nameRu: 'Детское печенье «Бегемотик Бонди» обогащённое кальцием 180г',
    nameEn: 'Baby Biscuits Begemotik Bondi with Calcium 180g',
    categoryId: 'cat_bondi_cookies',
    brand: 'Бегемотик Бонди',
    price: 12500,
    costPrice: 8200,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/24528625cac8f6ed03a94d1644072e8b.jpg',
    description: 'Suyaklar va tishlarning mustahkam o\'sishi uchun kalsiy va vitaminlar bilan boyitilgan klassik bolalar pechenyesi. 6 oylikdan boshlab.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 580, br_chilanzar: 290, br_samarkand: 240 },
    minStockAlert: 50,
    tags: ['бонди', 'печенье', 'кальций', 'детское печенье']
  },
  {
    id: 'prod_bondi_cookie_animals_80g',
    sku: 'BND-CK-ANM80',
    barcode: '4607065533055',
    nameUz: 'Begemotik Bondi: "Hayvonlarni o\'rganamiz" kalsiyli pechenye 80g (Zip)',
    nameRu: 'Детское печенье «Бегемотик Бонди» «Изучаем животных» 80г',
    nameEn: 'Baby Biscuits Begemotik Bondi Animals 80g',
    categoryId: 'cat_bondi_cookies',
    brand: 'Бегемотик Бонди',
    price: 7800,
    costPrice: 4900,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/f76473d29074bd34f6b42d090cc37953.jpg',
    description: 'Hayvonlar shaklidagi (mushukcha, toshbaqa, begemotcha) qiziqarli bolalar pechenyesi. Kalsiy va vitaminlarga boy, qulay zip-paket.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 430, br_chilanzar: 210, br_samarkand: 170 },
    minStockAlert: 40,
    tags: ['бонди', 'печенье', 'животные', 'кальций', 'zip']
  },
  {
    id: 'prod_bondi_cookie_banana_180g',
    sku: 'BND-CK-BAN180',
    barcode: '4607065533062',
    nameUz: 'Begemotik Bondi: Bananli bolalar pechenyesi 180g',
    nameRu: 'Детское печенье «Бегемотик Бонди» с бананом 180г',
    nameEn: 'Baby Biscuits Begemotik Bondi with Banana 180g',
    categoryId: 'cat_bondi_cookies',
    brand: 'Бегемотик Бонди',
    price: 12500,
    costPrice: 8200,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/6729bb49a96e244e59a5651c23359661.jpg',
    description: 'Banan pyuresi va B guruhi, C va PP vitaminlari bilan boyitilgan yumshoq bolalar pechenyesi. 5 oylikdan boshlab.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 490, br_chilanzar: 240, br_samarkand: 200 },
    minStockAlert: 40,
    tags: ['бонди', 'печенье', 'банан', 'детское питание']
  },

  // === СОКИ 200мл С ТРУБОЧКОЙ ===
  {
    id: 'prod_bondi_juice_apple_clear',
    sku: 'BND-JC-APCL',
    barcode: '4607065534014',
    nameUz: 'Begemotik Bondi: Tiniqlashtirilgan Olma sharbati 200ml',
    nameRu: 'Сок «Бегемотик Бонди» «Яблоко осветленный» 200мл',
    nameEn: 'Juice Begemotik Bondi Apple Clarified 200ml',
    categoryId: 'cat_bondi_juice',
    brand: 'Бегемотик Бонди',
    price: 4200,
    costPrice: 2700,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/85aae3690182858fd069036f205680c2.jpg',
    description: '100% tabiiy meva sharbati. Shakarsiz, konservantsiz, bo\'yoqsiz. 4 oylikdan boshlab tavsiya etiladi. Naychali qulay tetra-pak.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 650, br_chilanzar: 320, br_samarkand: 280 },
    minStockAlert: 60,
    tags: ['бонди', 'сок', 'яблоко', 'детский сок', 'kdv']
  },
  {
    id: 'prod_bondi_juice_apple_direct',
    sku: 'BND-JC-APDR',
    barcode: '4607065534021',
    nameUz: 'Begemotik Bondi: To\'g\'ridan-to\'g\'ri siqilgan Olma sharbati 200ml',
    nameRu: 'Сок «Бегемотик Бонди» «Яблоко, прямой отжим» 200мл',
    nameEn: 'Juice Begemotik Bondi Direct Apple 200ml',
    categoryId: 'cat_bondi_juice',
    brand: 'Бегемотик Бонди',
    price: 4500,
    costPrice: 2900,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/066abf9305745a26609a61a616a63021.jpg',
    description: 'Yangi uzilgan olmalardan to\'g\'ridan-to\'g\'ri siqilgan 100% sof sharbat. Shakarsiz va qo\'shimchalarsiz. 4 oylikdan.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 500, br_chilanzar: 250, br_samarkand: 210 },
    minStockAlert: 50,
    tags: ['бонди', 'сок', 'прямой отжим', 'яблоко']
  },
  {
    id: 'prod_bondi_juice_apple_grape',
    sku: 'BND-JC-APGR',
    barcode: '4607065534038',
    nameUz: 'Begemotik Bondi: Olma va Uzum sharbati 200ml',
    nameRu: 'Сок «Бегемотик Бонди» «Яблоко-Виноград» 200мл',
    nameEn: 'Juice Begemotik Bondi Apple & Grape 200ml',
    categoryId: 'cat_bondi_juice',
    brand: 'Бегемотик Бонди',
    price: 4200,
    costPrice: 2700,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/32bb44e4aba54244905ab1bc4c0ea0b4.jpg',
    description: '100% tabiiy olma va oq uzum sharbati. Shakarsiz, vitaminlarga boy. 6 oylikdan bolalar uchun.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 480, br_chilanzar: 240, br_samarkand: 200 },
    minStockAlert: 40,
    tags: ['бонди', 'сок', 'яблоко', 'виноград']
  },
  {
    id: 'prod_bondi_juice_apple_cherry',
    sku: 'BND-JC-APCH',
    barcode: '4607065534045',
    nameUz: 'Begemotik Bondi: Olma va Olcha (Vishnya) sharbati 200ml',
    nameRu: 'Сок «Бегемотик Бонди» «Яблоко-Вишня» 200мл',
    nameEn: 'Juice Begemotik Bondi Apple & Cherry 200ml',
    categoryId: 'cat_bondi_juice',
    brand: 'Бегемотик Бонди',
    price: 4200,
    costPrice: 2700,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/a6c53af3d123418707633ea4ae79d580.jpg',
    description: 'Olma va saralangan gilos-olcha sharbatining tabiiy uyg\'unligi. Shakarsiz, 5 oylikdan boshlab.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 460, br_chilanzar: 230, br_samarkand: 190 },
    minStockAlert: 40,
    tags: ['бонди', 'сок', 'яблоко', 'вишня']
  },
  {
    id: 'prod_bondi_juice_apple_peach',
    sku: 'BND-JC-APPC',
    barcode: '4607065534052',
    nameUz: 'Begemotik Bondi: Olma va Shaftoli sharbati 200ml',
    nameRu: 'Сок «Бегемотик Бонди» «Яблоко-Персик» 200мл',
    nameEn: 'Juice Begemotik Bondi Apple & Peach 200ml',
    categoryId: 'cat_bondi_juice',
    brand: 'Бегемотик Бонди',
    price: 4200,
    costPrice: 2700,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/9a602744a4be13dca11293e07deada07.jpg',
    description: 'Yumshoq mayin ta\'mli olma va shaftoli sharbati. Shakarsiz, tabiiy mineral va vitaminlar manbai.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 510, br_chilanzar: 250, br_samarkand: 210 },
    minStockAlert: 50,
    tags: ['бонди', 'сок', 'яблоко', 'персик']
  },
  {
    id: 'prod_bondi_juice_multifruit',
    sku: 'BND-JC-MLTF',
    barcode: '4607065534069',
    nameUz: 'Begemotik Bondi: Multifrukt sharbati 200ml',
    nameRu: 'Сок «Бегемотик Бонди» «Мультифрукт» 200мл',
    nameEn: 'Juice Begemotik Bondi Multifruit 200ml',
    categoryId: 'cat_bondi_juice',
    brand: 'Бегемотик Бонди',
    price: 4200,
    costPrice: 2700,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/da1ef54b3972a0aa3ec9b6b21e4fb876.jpg',
    description: 'Ekzotik va bog\' mevalari jamlangan boy ta\'mli 100% tabiiy sharbat. Shakarsiz, 6 oylikdan bolalarga.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 530, br_chilanzar: 260, br_samarkand: 220 },
    minStockAlert: 50,
    tags: ['бонди', 'сок', 'мультифрукт', 'детский сок']
  },

  // === НЕКТАРЫ ===
  {
    id: 'prod_bondi_nectar_smoothie',
    sku: 'BND-NCT-SMT',
    barcode: '4607065535011',
    nameUz: 'Begemotik Bondi: "Smuzi Banan-Qulupnay" meva nektari 200ml',
    nameRu: 'Нектар «Бегемотик Бонди» «Смузи банан-клубника» 200мл',
    nameEn: 'Nectar Begemotik Bondi Banana-Strawberry Smoothie 200ml',
    categoryId: 'cat_bondi_nectar',
    brand: 'Бегемотик Бонди',
    price: 4800,
    costPrice: 3100,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/873debaa6a8eafea80f220634761f612.jpg',
    description: '100% tabiiy meva eti (myakot) bilan quyuq smuzi-nektar. Banan va xushbo\'y qulupnay. 6 oylikdan boshlab.',
    expiryDays: 365,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 470, br_chilanzar: 230, br_samarkand: 190 },
    minStockAlert: 40,
    tags: ['бонди', 'нектар', 'смузи', 'банан', 'клубника']
  },

  // === ЧАЙ ТРАВЯНОЙ ===
  {
    id: 'prod_bondi_tea_fennel_25p',
    sku: 'BND-TEA-FEN25',
    barcode: '4607065536018',
    nameUz: 'Hippo Bondi & Friends: Fenxel bolalar o\'simlik choyi (25 paketcha, 25g)',
    nameRu: 'Детский травяной чай «Hippo Bondi & Friends» «Фенхель», 25 пакетиков 25г',
    nameEn: 'Herbal Baby Tea Hippo Bondi & Friends Fennel 25 Tea Bags 25g',
    categoryId: 'cat_bondi_tea',
    brand: 'Бегемотик Бонди',
    price: 16000,
    costPrice: 10500,
    unit: 'dona',
    image: 'https://kdv-group.com/uploads/catalog-offer/34dd3a938c7dbe57d98b092f6f117fcc.jpg',
    description: '100% tabiiy fenxel urug\'laridan tayyorlangan shifobaxsh choy. 4 oylikdan boshlab. Chaqaloqlarda ich dam bo\'lishi va koliklarni yengillatadi, ovqat hazm qilishni normallashtiradi. Shakarsiz, bo\'yoqsiz.',
    expiryDays: 730,
    isPopular: true,
    stockByBranch: { br_toshkent_main: 380, br_chilanzar: 190, br_samarkand: 150 },
    minStockAlert: 30,
    tags: ['бонди', 'чай', 'фенхель', 'детский чай', 'колики', 'kdv']
  }
];

fs.writeFileSync('src/data/kdv_bondi_products.json', JSON.stringify(bondiProducts, null, 2));
console.log('Successfully saved ' + bondiProducts.length + ' Бегемотик Бонди products into src/data/kdv_bondi_products.json');
